version: '3.8'
services:
  guardian:
    build: ./deploy
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
